framework:
    secret: '%env(APP_SECRET)%'
    router:
        utf8: true
    default_locale: en
    session:
        handler_id: null
        cookie_secure: auto
    csrf_protection: true
    form: true
    validation:
        enable_annotations: true
    translator:
        fallbacks: ['en']