services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Doctrine\Persistence\ManagerRegistry: '@doctrine'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        public: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
